create or replace
TYPE       XXPNA_GET_ALL_CART_ITEMS
   FORCE AS OBJECT
(
    USER_NAME          VARCHAR2(1000 BYTE),
    ITEM_NUMBER        VARCHAR2(1000 BYTE),
    ITEM_NAME          VARCHAR2(1000 BYTE),
    ITEM_DESCRIPTION   VARCHAR2(1000 BYTE),
    ITEM_QUANTITY      NUMBER,
    REQUEST_DATE       DATE,
    PRICE_LIST         NUMBER,
    CUSTOMER_NUMBER    VARCHAR2(200 BYTE), 
    ATTRIBUTE1         VARCHAR2(150 BYTE),
    ATTRIBUTE2         VARCHAR2(150 BYTE),
    ATTRIBUTE3         VARCHAR2(150 BYTE),
    ATTRIBUTE4         VARCHAR2(150 BYTE),
    ATTRIBUTE5         VARCHAR2(150 BYTE),
    ATTRIBUTE6         VARCHAR2(150 BYTE),
    ATTRIBUTE7         VARCHAR2(150 BYTE),
    ATTRIBUTE8         VARCHAR2(150 BYTE),
    ATTRIBUTE9         VARCHAR2(150 BYTE),
    ATTRIBUTE10        VARCHAR2(150 BYTE),
    ATTRIBUTE11        VARCHAR2(150 BYTE),
    ATTRIBUTE12        VARCHAR2(150 BYTE),
    ATTRIBUTE13        VARCHAR2(150 BYTE),
    ATTRIBUTE14        VARCHAR2(150 BYTE),
    ATTRIBUTE15        VARCHAR2(150 BYTE)
);